### ISSUE TITLE
Dark Signs Online

### ISSUE THREAD

**Issue by Doridian** [xmakina/darksigns.com#4]
Hey there,

I realized you grabbed the darksigns.com domain. Glad to see it revived :)

Personally, I was more involved with [Dark Signs Online](https://darksignsonline.com/) (which I managed to grab its domain today, funnily enough on the exact same day 0.8.1, the final release, was released).
Sadly it seems archive.org missed all versions of DSO :(

I am just reaching out here on the off-chance anyone has a version of the game client from back then laying around.

- Doridian

**Comment by Doridian** [comment]
Managed to recover all of it :)

**Comment by Doridian** [comment]
(However,  if someone happens to come accross the music for the game, that would also be great! Since the source does not include it...)

**Comment by xmakina** [comment]
That's very cool, glad you were able to find everything!
